### PR TITLE
Add LinkedIn Icon to Person Component

### PR DESCRIPTION
**Pull request by msschroe3**
### Changes
* Added support for LinkedIn Icon to the Person Component
* Made LinkedIn and Twitter Icons optional
* Added (crappy quality) favicon - do you know where we can get a better one?

### CODE REVIEW

**Comment by DSchau** [comment]
Deploy preview for *presentation-starter-kit* ready!

Built with commit 65838d4f4d9922797154ba5212ba6e5f95c1edd1

https://deploy-preview-2--presentation-starter-kit.netlify.com

**Comment by msschroe3** [comment]
Added another commit to get netlify working by forcing the Yarn version up to `1.5.1`. There's an issue with the version of Yarn (1.2.1) that netlify uses and the `workspaces` section of our `package.json`

```error An unexpected error occurred: "patterns.map is not a function"```

**Comment by msschroe3** [comment]
@DSchau - I don't have write access, so go ahead and merge it whenever

**Comment by DSchau** [comment]
🙌 whoops; thank you. I'll just add ya now.

**Pull request merged**
